version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.10.1
jobs:
  test:
    executor:
      name: node/default
      tag: '16.5'
    steps:
      - checkout
      - run:
          name: Install pkg-config
          command: sudo apt-get update -y && sudo apt-get install -y pkg-config libusb-1.0-0
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - slack/notify:
          event: fail
          branch_pattern: main|master
          template: basic_fail_1
      - slack/notify:
          event: pass
          branch_pattern: main|master
          template: basic_success_1

workflows:
  workflow:
    jobs:
      - test:
          context:
            - test
